#ifndef SOURCES_GAME_OBJECTS_CREATURES_ATTACK_POLICY_H
#define SOURCES_GAME_OBJECTS_CREATURES_ATTACK_POLICY_H


enum class AttackPolicy {
    Melee,
    Distance
};


#endif // SOURCES_GAME_OBJECTS_CREATURES_ATTACK_POLICY_H
