#ifndef SOURCES_GAME_OBJECTS_CREATURES_MOVEMENT_POLICY_H
#define SOURCES_GAME_OBJECTS_CREATURES_MOVEMENT_POLICY_H


enum class MovementPolicy {
    Stand,
    Walk
};


#endif // SOURCES_GAME_OBJECTS_CREATURES_MOVEMENT_POLICY_H
