#ifndef SOURCES_GAME_INTERACTIONS_INTERACTION_TYPE_H
#define SOURCES_GAME_INTERACTIONS_INTERACTION_TYPE_H


enum class InteractionType {
    None,
    Use
};


#endif // SOURCES_GAME_INTERACTIONS_INTERACTION_TYPE_H
